### ISSUE TITLE
header value `nil` causes error (but `publish` reports `:ok`)

### ISSUE THREAD

**Issue by derekkraan** [rabbitmq/rabbitmq-erlang-client#103]
Hi folks,

I'm pretty sure this is a bug, but I just want to make sure before I make an attempt to fix it.

If I publish a message with a header with value `nil`, then I get return value `:ok`, but the message isn't delivered to rabbitmq at all. Instead some process dies, and with it, the message.

Here's a simple example (apologies, this is Elixir code written with the AMQP library, but it calls through almost directly to `:amqp_client`):
```
AMQP.Basic.publish(ch, "requests", "", "foo", [headers: {"foo", :longstr, nil}])
:ok
```

And the output from `handle_sasl_reports: true`

```
iex(7)> [error] Process #PID<0.924.0> terminating
** (FunctionClauseError) no function clause matching in :rabbit_binary_generator.generate_table/1
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:146: :rabbit_binary_generator.generate_table({"foo", :longstr
, nil})
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl:1190: :rabbit_framing_amqp_0_9_1.encode_properties/1
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:190: :rabbit_binary_generator.ensure_content_encoded/2
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:68: :rabbit_binary_generator.build_simple_content_frames/4
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:311: :rabbit_writer.assemble_frames/5
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:341: :rabbit_writer.internal_send_command_async/3
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:209: :rabbit_writer.handle_message/3
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:193: :rabbit_writer.mainloop1/2
    (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:184: :rabbit_writer.mainloop/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Initial Call: :rabbit_writer.enter_mainloop/2
Ancestors: [#PID<0.921.0>, #PID<0.795.0>, #PID<0.793.0>, #PID<0.792.0>, :amqp_sup, #PID<0.696.0>]
Message Queue Length: 0
Messages: []
Links: [#PID<0.921.0>]
Dictionary: [process_name: {:rabbit_writer, {"client 172.20.0.4:57073 -> 172.20.0.3:5672", 4}}]
Trapping Exits: false
Status: :running
Heap Size: 2586
Stack Size: 27
Reductions: 406
[error] Child :writer of Supervisor #PID<0.921.0> (:amqp_channel_sup) terminated
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :rabbit_binary_generator.generate_table/1
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:146: :rabbit_binary_generator.generate_table({"foo", :lon
gstr, nil})
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl:1190: :rabbit_framing_amqp_0_9_1.encode_properties/1
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:190: :rabbit_binary_generator.ensure_content_encoded/2
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_binary_generator.erl:68: :rabbit_binary_generator.build_simple_content_frames/
4
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:311: :rabbit_writer.assemble_frames/5
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:341: :rabbit_writer.internal_send_command_async/3
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:209: :rabbit_writer.handle_message/3
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:193: :rabbit_writer.mainloop1/2
        (rabbit_common) /apps/public_interface/deps/rabbit_common/src/rabbit_writer.erl:184: :rabbit_writer.mainloop/2
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Pid: #PID<0.924.0>
Start Call: :rabbit_writer.start_link(#Port<0.27962>, 4, 131072, :rabbit_framing_amqp_0_9_1, #PID<0.923.0>, {"client 172.20.0.4:57073 -> 172.20.0.3:5672", 
4})
Restart: :transient
Shutdown: 30000
Type: :worker
[error] Child :writer of Supervisor #PID<0.921.0> (:amqp_channel_sup) caused shutdown
** (exit) :reached_max_restart_intensity
Start Call: :rabbit_writer.start_link(#Port<0.27962>, 4, 131072, :rabbit_framing_amqp_0_9_1, #PID<0.923.0>, {"client 172.20.0.4:57073 -> 172.20.0.3:5672", 
4})
Restart: :transient
Shutdown: 30000
Type: :worker
```

Expected behaviour would be an error return value.

I'd like to make an attempt to fix this issue, but I thought I'd ask here first whether anyone had any feedback. This is quite frustrating to debug if you're just getting started.

**Comment by michaelklishin** [comment]
This is not a bug. A headers table (map) is not a table in your case, it's a tuple, so `rabbit_binary_generator:generate_table/1` refuses to accept it.

**Comment by michaelklishin** [comment]
To clarify: the value is *not* expected to be a map. It must be a list of triplets, `{name, type, value}`. From the generated parser code:

``` erlang
-type amqp_field_type() ::
      'longstr' | 'signedint' | 'decimal' | 'timestamp' |
      'unsignedbyte' | 'unsignedshort' | 'unsignedint' |
      'table' | 'byte' | 'double' | 'float' | 'long' |
      'short' | 'bool' | 'binary' | 'void' | 'array'.
-type amqp_property_type() ::
      'shortstr' | 'longstr' | 'octet' | 'short' | 'long' |
      'longlong' | 'timestamp' | 'bit' | 'table'.

-type amqp_table() :: [{binary(), amqp_field_type(), amqp_value()}].
-type amqp_array() :: [{amqp_field_type(), amqp_value()}].
-type amqp_value() :: binary() |    % longstr
                      integer() |   % signedint
                      {non_neg_integer(), non_neg_integer()} | % decimal
                      amqp_table() |
                      amqp_array() |
                      byte() |      % byte
                      float() |     % double
                      integer() |   % long
                      integer() |   % short
                      boolean() |   % bool
                      binary() |    % binary
                      'undefined' | % void
                      non_neg_integer(). % timestamp
```

**Comment by derekkraan** [comment]
`[{"foo", :longstr, nil}]` is not a map, it is a list of triplets.

And besides that, returning `:ok` and subsequently failing silently to deliver a message to rabbitmq doesn't seem like desired behaviour.

**Comment by derekkraan** [comment]
Thanks for commenting so quickly btw.

**Comment by michaelklishin** [comment]
I don't see how the value in `[headers: {"foo", :longstr, nil}]` is an expected list, or even a map. We'd consider a PR that adds basic sanity checking to but the problem here comes down to the fact that channels are not responsible for serialisation, connections are.

**Comment by derekkraan** [comment]
Just in case: I'm using Elixir syntax because my Erlang is too rusty to rely on. That might be why it doesn't look like anything you'd recognize.

**Comment by michaelklishin** [comment]
Erlang doesn't have the concept of `nil`, so even if your code example contains a typo (it passes a tuple for `headers` and not a list), you cannot pass a `nil` from Elixir and assume the client will know what to do with it. The atom `undefined` is how `nil`/`null` and such are usually expressed. Or just leave the header out entirely.

Our team does not use GitHub issues for questions and discussions, please use rabbitmq-users for further questions (a PR with a specific set of changes we can evaluate doesn't have to go through the mailing list).

**Comment by michaelklishin** [comment]
@derekkraan thanks, our team is [capable of reading Elixir](https://github.com/rabbitmq/rabbitmq-cli).

**Comment by derekkraan** [comment]
That wasn't intended as an insult by the way, I just wasn't sure why we can't agree on the definition of a list or a tuple.

Anyways, message received, this isn't the place for discussion.

**Comment by michaelklishin** [comment]
There is no confusion about lists or tuples. They are no different between Erlang and Elixir. Your code clearly passes a single header instead of a list, I don't know if that's a typo or not. Either way, the value you want is

``` erlang
# a table with one header
[{<<"foo">>, longstr, undefined}]
```

``` elixir
[{"foo", :longstr, :undefined}]
```

**Comment by derekkraan** [comment]
You're right, I was missing a list in the example.

If I run this example with the missing list, then the result is the same. The library says `:ok` and the rabbit_writer dies in the background without having delivered the message to rabbitmq. I could paste in the whole stacktrace but that's not quite the point ([it comes out to this line](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_binary_generator.erl#L166)). The point is that I get `:ok` back, and then somewhere else there is a crash and the message never arrives in rabbitmq.

Anyways, I don't quite get the idea that my contribution to this discussion is welcome so if you'd like the last word then please be my guest.

**Comment by lukebakken** [comment]
> The library says :ok and the rabbit_writer dies in the background without having delivered the message to rabbitmq.

IMHO that is definitely a problem.

**Comment by michaelklishin** [comment]
Like I said earlier we'd appreciate a PR that makes `basic_publish` validate the inputs earlier. It's not obvious how we can do this without going through the protocol generator twice (which channels should not do) but there are no objections to the idea.
