### ISSUE TITLE
Unable to use TLS private key password parameter

### ISSUE THREAD

**Issue by Giri-Chintala** [rabbitmq/rabbitmq-erlang-client#36]
Current version of the client doesn't support password enabled SSL private-key although password is a standard TLS library.

The password option is not white listed in the client. See line 169 in https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_uri.erl

Here is the reference to discussion on this issue in google groups.
https://groups.google.com/forum/#!searchin/rabbitmq-users/giri/rabbitmq-users/GikyQd-TiDo/MOhF59MuAQAJ

**Comment by michaelklishin** [comment]
This is straightforward enough to get into `3.6.1` still. I'll look into it this week.
