### ISSUE TITLE
The client fails to compile on Erlang/OTP release 19.x

### ISSUE THREAD

**Issue by jlouis** [rabbitmq/rabbitmq-erlang-client#41]
Hi, just a quick heads up for things which will change in 19.x:

https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/include/amqp_gen_consumer_spec.hrl#L30-L42

The `-spec(init/1 :: ...)` form is supposedly going away and is not allowed anymore as a form. This means the current version of the `amqp_client` will not compile on this release. It is still some months out in the future, so there is no rush, but you may want to see if there are other places you get hit, eventually.

**Comment by michaelklishin** [comment]
Thank you for the heads-up!

**Comment by jlouis** [comment]
Gentle bump. This will soon become a problem for many. I can do the patch if necessary, and I think it falls outside the need for signing a contributor agreement. It is just a simple substitution.

Do you have work on this already, or should I go ahead and write a patch?

**Comment by dsrosario** [comment]
Hi,
This is a problem as Erlang OTP 19 is released. Please check my pull request (https://github.com/rabbitmq/rabbitmq-erlang-client/pull/63) for the patch.

**Comment by michaelklishin** [comment]
Fixed by @dsrosario in https://github.com/rabbitmq/rabbitmq-erlang-client/pull/63.
