### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dcy** [rabbitmq/rabbitmq-erlang-client#62]
Hi! the latest code can not compile.
```
===> Compiling /home/dcy/hisir/Server/hisir_msgs/_build/default/lib/amqp_client/src/amqp_connection_type_sup.erl failed
/home/dcy/hisir/Server/hisir_msgs/_build/default/lib/amqp_client/src/amqp_connection_type_sup.erl:51: undefined macro 'WORKER_WAIT'
```

**Comment by michaelklishin** [comment]
You need to make sure your `rabbit_common` is up-to-date with this client: [WORKER_WAIT is defined there](https://github.com/rabbitmq/rabbitmq-common/blob/master/include/rabbit.hrl#L157).

**Comment by dcy** [comment]
Sorry. Because i use rebar3, so i use this https://github.com/jbrisbin/rabbit_common.
This repo has not updated.
