### ISSUE TITLE
rabbitmq-erlang-client should define deps of syntax_tools and compiler

### ISSUE THREAD

**Issue by nestor5** [rabbitmq/rabbitmq-erlang-client#72]
with amqp_client in DEPS, release built by erlang.mk can't start:

{{function_clause,[{amqp_gen_connection,terminate,[{undef,[{erl_syntax,form_list,[[{attribute,1,file,{"src/time_compat.erl",1}},...

after adding syntax_tools into LOCAL_DEPS:

{{function_clause,[{amqp_gen_connection,terminate,[{undef,[{compile,forms,[[{attribute,1,file,{"src/time_compat.erl",1}},...

adding compiler into LOCAL_DEPS and it works

**Comment by essen** [comment]
PR ready to review and merge.

**Comment by michaelklishin** [comment]
Thank you, @nestor5 and @essen .

**Comment by michaelklishin** [comment]
FTR, we had to do https://github.com/rabbitmq/rabbitmq-erlang-client/commit/712f7b341b3aac20f8fdbb23fd960aea4d0f1f0f as well.
