### ISSUE TITLE
Publish version 3.6.6 on hex

### ISSUE THREAD

**Issue by nardopessoa** [rabbitmq/rabbitmq-erlang-client#74]
Hey, it seems the version 3.6.6 is not on [hex](https://hex.pm/) although it is tagged in the git repository.
Can you publish it?

Thanks a lot

**Comment by michaelklishin** [comment]
Sorry but we won't publish `3.6.6` to hex.pm. `3.6.7` will be on hex.pm shortly after that version is released.

**Comment by michaelklishin** [comment]
There's a `3.6.7` milestone up on hex.pm already IIRC. Just use that. It should be just as good as `3.6.6`.
